---
name: Cleanup Old Images
on: # yamllint disable-line rule:truthy
  schedule:
    - cron: "05 7 * * *" # 7:05 UTC everyday
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/cleanup-old-images.yml"
      
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
jobs:
  delete-older-than-90:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete Images Older Than 90 Days
        if: false
        uses: dataaxiom/ghcr-cleanup-action@cd0cdb900b5dbf3a6f2cc869f0dbb0b8211f50c4 # v1.0.16
        with:
          token: ${{ secrets.PAT_RENOVATEBOT }}
          older-than: 90 days
          #delete-orphaned-images: true
          #delete-untagged: true
          owner: ${{ github.repository_owner }}
          #repository: ${{ github.event.repository.name }}
          packages: homeserver-centos-bootc/**/*,homeserver-centos-bootc/*,homeserver-*,homeserver-**
          expand-packages: true
          keep-n-tagged: 7
          #keep-n-untagged: 7
          # dry-run: true

      - name: Delete Untagged Images
        uses: dataaxiom/ghcr-cleanup-action@cd0cdb900b5dbf3a6f2cc869f0dbb0b8211f50c4 # v1.0.16
        with:
          delete-untagged: true
          packages: homeserver-bootc/homeserver-centos-bootc,homeserver-bootc/homeserver-gui-bootc

      - name: Delete old PR Images
        uses: dataaxiom/ghcr-cleanup-action@cd0cdb900b5dbf3a6f2cc869f0dbb0b8211f50c4 # v1.0.16
        with:
          delete-tags: pr-*
          older-than: 7 days
          packages: homeserver-bootc/homeserver-centos-bootc,homeserver-bootc/homeserver-gui-bootc
      
      - name: Delete ghost images
        uses: dataaxiom/ghcr-cleanup-action@cd0cdb900b5dbf3a6f2cc869f0dbb0b8211f50c4 # v1.0.16
        with:
          delete-ghost-images: true
          packages: homeserver-bootc/homeserver-centos-bootc,homeserver-bootc/homeserver-gui-bootc

      - name: Clean up old images
        uses: dataaxiom/ghcr-cleanup-action@cd0cdb900b5dbf3a6f2cc869f0dbb0b8211f50c4 # v1.0.16
        with:
          keep-n-tagged: 10
          exclude-tags: latest
          older-than: 14 days
          packages: homeserver-bootc/homeserver-centos-bootc,homeserver-bootc/homeserver-gui-bootc